services:
  db:
    image: postgres:latest
    container_name: bot_database_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5444:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    container_name: bot_discord
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
