name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier --if-present -- --write .

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -x  
            echo "Connected to VPS"
            cd dev/bot_discord
            echo "Changed directory to dev/bot_discord"
            git pull
            echo "Git pull completed"
            npm install
            echo "npm install completed"
          EOF

      - name: Start Discord bot with PM2
        run: |
          ssh -tt ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOSSH'
            cd dev/bot_discord

            # Vérifier si l'application PM2 existe déjà
            if pm2 show discord-bot >/dev/null 2>&1; then
              echo "Restarting existing PM2 process..."
              pm2 restart discord-bot
            else
              echo "Starting new PM2 process..."
              pm2 start index.js --name "discord-bot"
            fi
            
          EOSSH
