name: Deploy to VPS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Add VPS to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Vous pouvez spécifier la version de Node.js appropriée

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: |
        prettier --check .
      continue-on-error: true  # Continue même si des erreurs sont trouvées
      env:
        CI: true  # Définit CI=true pour Prettier

    - name: Display Prettier errors
      if: ${{ failure() }}
      run: |
        echo "Prettier errors:"
        prettier --check . --list-different

    - name: Run ESLint
      run: |
        eslint .
      continue-on-error: true 

    - name: Display ESLint errors
      if: ${{ failure() }}
      run: |
        echo "ESLint errors:"
        eslint --format=stylish .

    - name: Deploy to VPS
      run: |
        ssh -tt ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "Connected to VPS"
          cd dev/bot_discord
          echo "I'm in the directory"
          git pull
          echo "Pulled!"
          npm install
          echo "Dependencies installed"
        EOF
      timeout-minutes: 5

    - name: Print debug info after deployment
      run: |
        echo "Debug: Deployment step finished"
